<?php
$posts_query = "CREATE TABLE posts (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_ID INT NOT NULL,
title VARCHAR(100) NOT NULL,
body TEXT,
create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)";
